name: W3 CLI Integration Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  w3-cli-integration:
    name: W3 CLI Integration Test
    runs-on: ubuntu-latest
    environment: STORACHA_KEY
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create .env file for tests
        run: |
          echo "STORACHA_KEY=${{ secrets.STORACHA_KEY }}" >> .env
          echo "STORACHA_PROOF=${{ secrets.STORACHA_PROOF }}" >> .env

      - name: Run W3 CLI integration test
        run: npm run test:w3-cli
        env:
          NODE_OPTIONS: '--experimental-vm-modules --no-warnings'

      - name: Clean up test artifacts
        if: always()
        run: npm run clean

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [w3-cli-integration]
    if: always()
    steps:
      - name: Notify Success
        if: needs.w3-cli-integration.result == 'success'
        run: |
          echo "✅ W3 CLI integration test passed successfully!"
          echo "🎉 OrbitDB Storacha W3 CLI integration is working correctly"

      - name: Notify Failure
        if: needs.w3-cli-integration.result == 'failure'
        run: |
          echo "❌ W3 CLI integration test failed"
          echo "🔍 Please check the logs above for details"
          exit 1
